### ISSUE TITLE
qsmxt crashed

### ISSUE THREAD

**Issue by chouyiyu** [QSMxT/QSMxT#141]
Dear qsmxt developers:
I got the following error message when running qsmxt from the command line:
"qsmxt 20241106-8213951-MW_bids --premade 'epi' --auto_yes"
It looks like the output file name of the brain mask should not be assigned.
I would appreciate it if you can let me know how to fix it, Thanks for the time and help!!

Sincerely,
Yiyu

241129-15:50:15,863 nipype.workflow WARNING:
         [Node] Error on "qsmxt-workflow.sub-8213951.ses-20241106.qsmxt_acq-ax2dt2starphasegrep315mm_run-01.mask-intermediate_workflow.fsl-bet" (/ISFILE3/USERS/chouy/Projects/QSM/20241106-8213951-MW_bids/derivatives/qsmxt-workflow/sub-8213951/ses-20241106/qsmxt_acq-ax2dt2starphasegrep315mm_run-01/mask-intermediate_workflow/fsl-bet)
241129-15:50:15,868 nipype.workflow INFO:
         [Node] Finished "fsl-bet", elapsed time 0.247434s.
241129-15:50:15,871 nipype.workflow WARNING:
         Storing result file without outputs
241129-15:50:15,875 nipype.workflow WARNING:
         [Node] Error on "qsmxt-workflow.sub-8213951.ses-20241106.qsmxt_acq-ax2dt2starphasegrep315mm_run-01.mask_workflow.fsl-bet" (/ISFILE3/USERS/chouy/Projects/QSM/20241106-8213951-MW_bids/derivatives/qsmxt-workflow/sub-8213951/ses-20241106/qsmxt_acq-ax2dt2starphasegrep315mm_run-01/mask_workflow/fsl-bet)
241129-15:50:17,507 nipype.workflow ERROR:
         Node fsl-bet failed to run on host cc0pipcsti.
241129-15:50:17,510 nipype.workflow ERROR:
         Saving crash info to /ISFILE3/USERS/chouy/Projects/QSM/crash-20241129-155017-chouy-fsl-bet-18a21aca-3105-43fe-a181-90a64e046d63.pklz
Traceback (most recent call last):
  File "/home/chouy/anaconda2/envs/qsmxt/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/home/chouy/anaconda2/envs/qsmxt/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/home/chouy/anaconda2/envs/qsmxt/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/home/chouy/anaconda2/envs/qsmxt/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node fsl-bet.

Cmdline:
        bet /ISFILE3/USERS/chouy/Projects/QSM/20241106-8213951-MW_bids/derivatives/qsmxt-workflow/sub-8213951/ses-20241106/qsmxt_acq-ax2dt2starphasegrep315mm_run-01/mask_workflow/mrt_correct-inhomogeneity/sub-8213951_ses-20241106_acq-ax2dt2starphasegrep315mm_run-01_echo-01_part-mag_MEGRE_canonical_combined_makehomogeneous.nii sub-8213951_ses-20241106_acq-ax2dt2starphasegrep315mm_run-01_echo-01_part-mag_MEGRE_canonical_combined_makehomogeneous_bet.nii.gz -m sub-8213951_ses-20241106_acq-ax2dt2starphasegrep315mm_run-01_echo-01_part-mag_MEGRE_canonical_combined_makehomogeneous_bet-mask.nii.gz -f 0.500000
Stdout:

        Usage:    bet <input> <output> [options]

        Main bet2 options:
          -o          generate brain surface outline overlaid onto original image
          -m          generate binary brain mask
          -s          generate approximate skull image
          -n          don't generate segmented brain image output
          -f <f>      fractional intensity threshold (0->1); default=0.5; smaller values give larger brain outline estimates
          -g <g>      vertical gradient in fractional intensity threshold (-1->1); default=0; positive values give larger brain outline at bottom, smaller at top
          -r <r>      head radius (mm not voxels); initial surface sphere is set to half of this
          -c <x y z>  centre-of-gravity (voxels not mm) of initial mesh surface.
          -t          apply thresholding to segmented brain image and mask
          -e          generates brain surface as mesh in .vtk format

        Variations on default bet2 functionality (mutually exclusive options):
          (default)   just run bet2
          -R          robust brain centre estimation (iterates BET several times)
          -S          eye & optic nerve cleanup (can be useful in SIENA - disables -o option)
          -B          bias field & neck cleanup (can be useful in SIENA)
          -Z          improve BET if FOV is very small in Z (by temporarily padding end slices)
          -F          apply to 4D FMRI data (uses -f 0.3 and dilates brain mask slightly)
          -A          run bet2 and then betsurf to get additional skull and scalp surfaces (includes registrations)
          -A2 <T2>    as with -A, when also feeding in non-brain-extracted T2 (includes registrations)

        Miscellaneous options:
          -v          verbose (switch on diagnostic messages)
          -h          display this help, then exits
          -d          debug (don't delete temporary intermediate images)

Stderr:

Traceback:
        Traceback (most recent call last):
          File "/home/chouy/anaconda2/envs/qsmxt/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
            setattr(outputs, key, val)
          File "/home/chouy/anaconda2/envs/qsmxt/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
            value = super(File, self).validate(objekt, name, value, return_pathlike=True)
          File "/home/chouy/anaconda2/envs/qsmxt/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
            self.error(objekt, name, str(value))
          File "/home/chouy/anaconda2/envs/qsmxt/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
            raise TraitError(
        traits.trait_errors.TraitError: The 'out_file' trait of a Bet2OutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/ISFILE3/USERS/chouy/Projects/QSM/20241106-8213951-MW_bids/derivatives/qsmxt-workflow/sub-8213951/ses-20241106/qsmxt_acq-ax2dt2starphasegrep315mm_run-01/mask_workflow/fsl-bet/sub-8213951_ses-20241106_acq-ax2dt2starphasegrep315mm_run-01_echo-01_part-mag_MEGRE_canonical_combined_bet.nii.gz' <class 'str'> was specified.

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/home/chouy/anaconda2/envs/qsmxt/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 400, in run
            outputs = self.aggregate_outputs(runtime)
          File "/home/chouy/anaconda2/envs/qsmxt/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
            raise FileNotFoundError(msg)
        FileNotFoundError: No such file or directory '/ISFILE3/USERS/chouy/Projects/QSM/20241106-8213951-MW_bids/derivatives/qsmxt-workflow/sub-8213951/ses-20241106/qsmxt_acq-ax2dt2starphasegrep315mm_run-01/mask_workflow/fsl-bet/sub-8213951_ses-20241106_acq-ax2dt2starphasegrep315mm_run-01_echo-01_part-mag_MEGRE_canonical_combined_bet.nii.gz' for output 'out_file' of a Bet2Interface interface

**Comment by astewartau** [comment]
Hi @chouyiyu, thanks for using QSMxT and for your patience in getting to this! I have been away for a time and can now look at this. 

From the output it looks like you are running QSMxT via your own anaconda environment in `home/chouy/anaconda2/envs/qsmxt`. The error you are getting looks like a different version of BET than the one packaged in the container. See the following output and how it is different from the BET instructions on your end:

```bash
~: bet

Part of FSL (build 504)
BET (Brain Extraction Tool) v2.1 - FMRIB Analysis Group, Oxford

Usage: 
bet2 <input_fileroot> <output_fileroot> [options]

Optional arguments (You may optionally specify one or more of):
        -o,--outline    generate brain surface outline overlaid onto original image
        -m,--mask <m>   generate binary brain mask
        -s,--skull      generate approximate skull image
        -n,--nooutput   don't generate segmented brain image output
        -f <f>          fractional intensity threshold (0->1); default=0.5; smaller values give larger brain outline estimates
        -g <g>          vertical gradient in fractional intensity threshold (-1->1); default=0; positive values give larger brain outline at bottom, smaller at top
        -r,--radius <r> head radius (mm not voxels); initial surface sphere is set to half of this
        -w,--smooth <r> smoothness factor; default=1; values smaller than 1 produce more detailed brain surface, values larger than one produce smoother, less detailed surface
        -c <x y z>      centre-of-gravity (voxels not mm) of initial mesh surface.
        -t,--threshold  -apply thresholding to segmented brain image and mask
        -e,--mesh       generates brain surface as mesh in vtk format
        -v,--verbose    switch on diagnostic messages
        -h,--help       displays this help, then exits
```

This indicates that you are either running QSMxT using the transparent singularity version for HPCs (https://qsmxt.github.io/QSMxT/installation#hpc-installation) or the CVMFS version, and in either case your paths are not set up correctly to find the correct BET executable. You may also be attempting a 'bare metal' installation where you manually install all QSMxT dependencies natively. This bare metal style is not recommended as it can affect computational reproducibility and be very challenging to setup. 

As a first step, you can run `which bet` to confirm where the incorrect binary is coming from. If you are running from inside the container, it should give:

```bash
Apptainer> which bet
/bin/bet
```

Otherwise, it should identify the path containing the executables for the specific container version you are using:

```bash
(qsmxt) ~: which bet
/cvmfs/neurodesk.ardc.edu.au/containers/qsmxt_7.3.2_20250220/bet
```

**Comment by astewartau** [comment]
Hi @chouyiyu, I'm closing this issue for now, but please feel free to re-open if you are still having issues with QSMxT and hopefully we can resolve them.
