### ISSUE TITLE
Request for instructions of implementing NextQSM

### ISSUE THREAD

**Issue by anniepan-pumc** [QSMxT/QSMxT#142]
Hi! I am here to ask for help for error when implementing NextQSM algorithms. After using commend `qsmxt /neurodesktop-storage/bids /neurodesktop-storage/qsm --masking_algorithm bet --masking_input phase --combine_phase true --qsm_algorithm nextqsm --unwrapping_algorithm romeo --bf_algorithm vsharp `, Error attached below happend:

`  Currently running:
                       * qsmxt-workflow.sub-svd001005.ses-20211107.qsmxt_acq-qsm3dtrap24echo2mm_run-01.mrt_romeo_combine-phase
241216-13:47:18,599 nipype.workflow INFO:
	 [Node] Finished "mrt_romeo_combine-phase", elapsed time 294.317205s.
241216-13:47:19,185 nipype.workflow INFO:
	 [Job 6] Completed (qsmxt-workflow.sub-svd001005.ses-20211107.qsmxt_acq-qsm3dtrap24echo2mm_run-01.mrt_romeo_combine-phase).
241216-13:47:19,187 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 14.04/14.04, Free processors: 14/14.
241216-13:47:19,208 nipype.workflow INFO:
	 [Node] Setting-up "qsmxt-workflow.sub-svd001005.ses-20211107.qsmxt_acq-qsm3dtrap24echo2mm_run-01.qsm_workflow.nibabel-numpy_normalize-freq" in "/neurodesktop-storage/qsm_nextqsm/qsmxt-workflow/sub-svd001005/ses-20211107/qsmxt_acq-qsm3dtrap24echo2mm_run-01/qsm_workflow/nibabel-numpy_normalize-freq".
241216-13:47:19,216 nipype.workflow INFO:
	 [Node] Executing "nibabel-numpy_normalize-freq" <qsmxt.interfaces.nipype_interface_processphase.FreqToNormalizedInterface>
241216-13:47:19,323 nipype.workflow INFO:
	 [Node] Finished "nibabel-numpy_normalize-freq", elapsed time 0.105577s.
241216-13:47:21,193 nipype.workflow INFO:
	 [Job 8] Completed (qsmxt-workflow.sub-svd001005.ses-20211107.qsmxt_acq-qsm3dtrap24echo2mm_run-01.qsm_workflow.nibabel-numpy_normalize-freq).
241216-13:47:21,195 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 1 jobs ready. Free memory (GB): 14.04/14.04, Free processors: 14/14.
241216-13:47:21,217 nipype.workflow INFO:
	 [Node] Setting-up "qsmxt-workflow.sub-svd001005.ses-20211107.qsmxt_acq-qsm3dtrap24echo2mm_run-01.qsm_workflow.nextqsm" in "/neurodesktop-storage/qsm_nextqsm/qsmxt-workflow/sub-svd001005/ses-20211107/qsmxt_acq-qsm3dtrap24echo2mm_run-01/qsm_workflow/nextqsm".
241216-13:47:21,225 nipype.workflow INFO:
	 [Node] Executing "nextqsm" <qsmxt.interfaces.nipype_interface_nextqsm.NextqsmInterface>
241216-13:47:21,799 nipype.workflow INFO:
	 [Node] Finished "nextqsm", elapsed time 0.573626s.
241216-13:47:21,801 nipype.workflow WARNING:
	 [Node] Error on "qsmxt-workflow.sub-svd001005.ses-20211107.qsmxt_acq-qsm3dtrap24echo2mm_run-01.qsm_workflow.nextqsm" (/neurodesktop-storage/qsm_nextqsm/qsmxt-workflow/sub-svd001005/ses-20211107/qsmxt_acq-qsm3dtrap24echo2mm_run-01/qsm_workflow/nextqsm)
241216-13:47:23,202 nipype.workflow ERROR:
	 Node nextqsm failed to run on host ce96cfb32f75.
241216-13:47:23,203 nipype.workflow ERROR:
	 Saving crash info to /opt/crash-20241216-134723-root-nextqsm-71cd00d3-aa6c-44dc-95d3-6b51bbae0290.pklz
Traceback (most recent call last):
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node nextqsm.

Cmdline:
	nextqsm /neurodesktop-storage/qsm_nextqsm/qsmxt-workflow/sub-svd001005/ses-20211107/qsmxt_acq-qsm3dtrap24echo2mm_run-01/qsm_workflow/nibabel-numpy_normalize-freq/sub-svd001005_ses-20211107_acq-qsm3dtrap24echo2mm_run-01_echo-01_part-phase_MEGRE_scaled_resampled_B0_normalized.nii /neurodesktop-storage/qsm_nextqsm/qsmxt-workflow/sub-svd001005/ses-20211107/qsmxt_acq-qsm3dtrap24echo2mm_run-01/mask_workflow/scipy_numpy_nibabel_bet_erode/sub-svd001005_ses-20211107_acq-qsm3dtrap24echo2mm_run-01_echo-01_part-mag_MEGRE_resampled_combined_bet-mask_ero.nii.gz sub-svd001005_ses-20211107_acq-qsm3dtrap24echo2mm_run-01_echo-01_part-phase_MEGRE_scaled_resampled_B0_normalized_nextqsm.nii.gz
Stdout:

Stderr:
	Illegal instruction
Traceback:
	RuntimeError: subprocess exited with code 132.

241216-13:47:23,208 nipype.workflow INFO:
	 [MultiProc] Running 0 tasks, and 0 jobs ready. Free memory (GB): 14.04/14.04, Free processors: 14/14.
241216-13:47:25,208 nipype.workflow INFO:
	 ***********************************
241216-13:47:25,209 nipype.workflow ERROR:
	 could not run node: qsmxt-workflow.sub-svd001005.ses-20211107.qsmxt_acq-qsm3dtrap24echo2mm_run-01.qsm_workflow.nextqsm
241216-13:47:25,210 nipype.workflow INFO:
	 crashfile: /opt/crash-20241216-134723-root-nextqsm-71cd00d3-aa6c-44dc-95d3-6b51bbae0290.pklz
241216-13:47:25,210 nipype.workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "/opt/miniconda-4.7.12.1/bin/qsmxt", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/qsmxt/cli/main.py", line 1796, in main
    wf.run(
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 224, in run
    raise error from cause
RuntimeError: Traceback (most recent call last):
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)
nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node nextqsm.

Cmdline:
	nextqsm /neurodesktop-storage/qsm_nextqsm/qsmxt-workflow/sub-svd001005/ses-20211107/qsmxt_acq-qsm3dtrap24echo2mm_run-01/qsm_workflow/nibabel-numpy_normalize-freq/sub-svd001005_ses-20211107_acq-qsm3dtrap24echo2mm_run-01_echo-01_part-phase_MEGRE_scaled_resampled_B0_normalized.nii /neurodesktop-storage/qsm_nextqsm/qsmxt-workflow/sub-svd001005/ses-20211107/qsmxt_acq-qsm3dtrap24echo2mm_run-01/mask_workflow/scipy_numpy_nibabel_bet_erode/sub-svd001005_ses-20211107_acq-qsm3dtrap24echo2mm_run-01_echo-01_part-mag_MEGRE_resampled_combined_bet-mask_ero.nii.gz sub-svd001005_ses-20211107_acq-qsm3dtrap24echo2mm_run-01_echo-01_part-phase_MEGRE_scaled_resampled_B0_normalized_nextqsm.nii.gz
Stdout:

Stderr:
	Illegal instruction
Traceback:
	RuntimeError: subprocess exited with code 132.`

Could you please tell me the proper way to implement nextqsm algorithm you provide in QSMxT algorithms? Many thanks.

**Comment by astewartau** [comment]
Hi @anniepan-pumc, thanks for your patience in getting to this as I was away for a time. 

That's an error I haven't encountered before. The `illegal instruction` message in `stderr` points to possibly some incompatibility issue.

Do you know what OS and CPU you used for this? Were you using the Docker container or running via Neurodesk?

**Comment by anniepan-pumc** [comment]
Thanks for reply! @astewartau  The virtual machine I used is based on docker desktop on Mac M4 chip. I have tried both Docker and Neurodesk. This question happened when I use QSMxT on Neurodesk.

**Comment by astewartau** [comment]
Hi @anniepan-pumc, can you try deactivating Rosetta and run through qemu - in the docker settings?
