### ISSUE TITLE
add clear error message if user has less memory than required to run

### ISSUE THREAD

**Issue by stebo85** [QSMxT/QSMxT#23]
if not args.n_procs:
        available_ram_gb = psutil.virtual_memory().available / 1e9
        args.n_procs = min(int(available_ram_gb / 6), n_cpus)

This currently fails with:

usage: tgv_qsm [-h] -p PHASE -m MASK [-o OUTPUT_SUFFIX]
               [--alpha ALPHA ALPHA | --factors FACTORS [FACTORS ...]]
               [-e EROSIONS] [-i ITERATIONS [ITERATIONS ...]]
               [-f FIELDSTRENGTH] [-t ECHOTIME] [-s] [--ignore-orientation]
               [--save-laplacian] [--output-physical] [--no-resampling]
               [--vis] [-v]
tgv_qsm: error: argument -p/--phase is required
Traceback (most recent call last):
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 148, in __init__
    mp_context=mp_context,
TypeError: __init__() got an unexpected keyword argument 'initializer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/QSMxT/run_2_qsm.py", line 676, in <module>
    'n_procs': args.n_procs
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 617, in run
    runner = plugin_mod(plugin_args=plugin_args)
  File "/opt/miniconda-latest/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 152, in __init__
    self.pool = ProcessPoolExecutor(max_workers=self.processors)
  File "/opt/miniconda-latest/lib/python3.6/concurrent/futures/process.py", line 394, in __init__
    raise ValueError("max_workers must be greater than 0")
ValueError: max_workers must be greater than 0

which is confusing for people

**Comment by stebo85** [comment]
this is implemented.
