### ISSUE TITLE
Suggested fix: match segmentation with qsm in run_5

### ISSUE THREAD

**Issue by thomshaw92** [QSMxT/QSMxT#31]
When I try and run run_5.py, I noticed that the segmentation and qsm were mismatched because I hadn't acquired a T1w for one of my datasets (so it wasn't segmented).
Would suggest matching filenames instead?
```
Analysing file sub-002_ses-01_acq-AspirePC2PGRE16MEaspire1mmisonew_run-1_echo-1_part-phase_MEGRE_scaled_qsm_000_composite_average.nii with segmentation sub-003_ses-01_acq-BrainAndSpine_run-1_T1w_segmentation_nii_trans.nii
Traceback (most recent call last):
  File "/opt/QSMxT/run_5_analysis.py", line 135, in <module>
    label_stats = get_stats(labels, seg, qsm)
  File "/opt/QSMxT/run_5_analysis.py", line 54, in get_stats
    qsm_values = qsm[np.logical_and(qsm != 0, qsm_seg)]
ValueError: operands could not be broadcast together with shapes (7768320,) (9241600,)
```

**Comment by astewartau** [comment]
This was fixed a while ago in [v4.0.0](https://github.com/QSMxT/QSMxT/releases/tag/v4.0.0). :smile:
