### ISSUE TITLE
Problem with nproc running on HPCs

### ISSUE THREAD

**Issue by thomshaw92** [QSMxT/QSMxT#38]
Having an issue with running on HPCs...
```
(qsmxt) s4320766@tinaroo1:.../project/stimmri/neurocommand> python3 ../QSMxT/run_2_qsm.py -h
OpenBLAS blas_thread_init: pthread_create failed for thread 42 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 50 current, 514567 max
OpenBLAS blas_thread_init: pthread_create failed for thread 43 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 50 current, 514567 max
OpenBLAS blas_thread_init: pthread_create failed for thread 44 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 50 current, 514567 max
OpenBLAS blas_thread_init: pthread_create failed for thread 45 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 50 current, 514567 max
OpenBLAS blas_thread_init: pthread_create failed for thread 46 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 50 current, 514567 max
OpenBLAS blas_thread_init: pthread_create failed for thread 47 of 48: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 50 current, 514567 max
Traceback (most recent call last):
  File "../QSMxT/run_2_qsm.py", line 8, in <module>
    from nipype.interfaces.fsl import BET, ImageMaths, ImageStats, MultiImageMaths, CopyGeom, Merge, UnaryMaths
  File "/home/s4320766/miniconda3/envs/qsmxt/lib/python3.6/site-packages/nipype/__init__.py", line 18, in <module>
    from .utils.config import NipypeConfig
  File "/home/s4320766/miniconda3/envs/qsmxt/lib/python3.6/site-packages/nipype/utils/config.py", line 19, in <module>
    import numpy as np
  File "/home/s4320766/miniconda3/envs/qsmxt/lib/python3.6/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/s4320766/miniconda3/envs/qsmxt/lib/python3.6/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/s4320766/miniconda3/envs/qsmxt/lib/python3.6/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/s4320766/miniconda3/envs/qsmxt/lib/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
KeyboardInterrupt
Segmentation fault
(qsmxt) s4320766@tinaroo1:.../project/stimmri/neurocommand> 

```

Not sure if this is an issue with the NPROCS or if I am doing something else wrong? running through Neurodesk

**Comment by stebo85** [comment]
Dear Thom,

It could be a specific problem on Tinaroo as this is an MPI cluster and my first guess is that it tries to use more CPU cores than it's allowed to. 

How many cores did you request in the job? Can you try to set the amount of cores manually via the command line option of QSMxT? Another idea would be limiting the cores to 1 and see if this still comes up (then it could be a library from Tinaroo overwriting a library in the container)

**Comment by thomshaw92** [comment]
Yup! Was the issue. 
I limited the number of cores in the script explicitly and that solved it.
