### ISSUE TITLE
threshold flag throws error

### ISSUE THREAD

**Issue by korbinian90** [QSMxT/QSMxT#56]
On the current master ([44ed1e9](https://github.com/QSMxT/QSMxT/commit/44ed1e9b27244f406a85c1b799db6f3a96ac9c29))  I tried
`python3 ./run_2_qsm.py ../data/bids ../data/test --threshold 50`

which resulted in 
```
INFO: Running QSMxT v1.1.11-33-g44ed1e (commit date: Tue Jul 26 15:37:09 2022 +100)
INFO: Command: ./run_2_qsm.py ../data/bids ../data/test --threshold 50
INFO: Running with 4 procesors.
220726-11:23:51,644 nipype.utils WARNING:
         A newer version (1.8.3) of nipy/nipype is available. You are using 1.8.2
Traceback (most recent call last):
  File "/neurodesktop-storage/qsmxt/./run_2_qsm.py", line 643, in <module>
    wf = init_workflow()
  File "/neurodesktop-storage/qsmxt/./run_2_qsm.py", line 41, in init_workflow
    [init_subject_workflow(subject) for subject in subjects]
  File "/neurodesktop-storage/qsmxt/./run_2_qsm.py", line 41, in <listcomp>
    [init_subject_workflow(subject) for subject in subjects]
  File "/neurodesktop-storage/qsmxt/./run_2_qsm.py", line 60, in init_subject_workflow
    [init_session_workflow(subject, session) for session in sessions]
  File "/neurodesktop-storage/qsmxt/./run_2_qsm.py", line 60, in <listcomp>
    [init_session_workflow(subject, session) for session in sessions]
  File "/neurodesktop-storage/qsmxt/./run_2_qsm.py", line 86, in init_session_workflow
    [init_run_workflow(subject, session, run) for run in runs]
  File "/neurodesktop-storage/qsmxt/./run_2_qsm.py", line 86, in <listcomp>
    [init_run_workflow(subject, session, run) for run in runs]
  File "/neurodesktop-storage/qsmxt/./run_2_qsm.py", line 241, in init_run_workflow
    wf.connect([
  File "/root/miniconda3/lib/python3.9/site-packages/nipype/pipeline/engine/workflows.py", line 161, in connect
    self._check_nodes(newnodes)
  File "/root/miniconda3/lib/python3.9/site-packages/nipype/pipeline/engine/workflows.py", line 761, in _check_nodes
    if node.name in node_names:
AttributeError: 'int' object has no attribute 'name'
```

**Comment by astewartau** [comment]
Thanks for this report! This was because the `threshold` parameter of the masking node was not set properly, and instead, the node itself was replaced with an integer threshold value. 

https://github.com/QSMxT/QSMxT/commit/3690a180b79e4104e832c65732284efccaada332
