### ISSUE TITLE
Crash of current master

### ISSUE THREAD

**Issue by korbinian90** [QSMxT/QSMxT#57]
Commit used: [44ed1e9](https://github.com/QSMxT/QSMxT/commit/44ed1e9b27244f406a85c1b799db6f3a96ac9c29)
Command:  `./run_2_qsm.py ../data/qsmxt-test-battery-bids-reduced/bids ../data/battery_twopass_magnitude-based-hole-1 --masking magnitude-based --fill_strength 1`

I tried reverting my container back to the original qsmxt container (as I suspected my environment modifications might have caused it) and I'm still having this problem.
I wanted to use the new master, as it would be easier to do masking experiments with the twopass option.
```
INFO: Running QSMxT v1.1.11-33-g44ed1e (commit date: Tue Jul 26 15:37:09 2022 +100)
INFO: Command: ./run_2_qsm.py ../data/qsmxt-test-battery-bids-reduced/bids ../data/battery_twopass_magnitude-based-hole-1 --masking magnitude-based --fill_strength 1
INFO: Running with 4 procesors.
220727-12:21:23,808 nipype.utils WARNING:
         A newer version (1.8.3) of nipy/nipype is available. You are using 1.6.0
220727-12:21:24,113 nipype.workflow INFO:
         Workflow workflow_qsm settings: ['check', 'execution', 'logging', 'monitoring']
220727-12:21:24,411 nipype.workflow INFO:
         Running in parallel.
220727-12:21:24,415 nipype.workflow INFO:
         [MultiProc] Running 0 tasks, and 18 jobs ready. Free memory (GB): 22.10/22.10, Free processors: 4/4.
220727-12:21:24,484 nipype.workflow INFO:
         [Job 0] Cached (workflow_qsm.sub-basel-3depi-P001.ses-1.run-1.nibabel_scale-phase).
220727-12:21:24,502 nipype.workflow INFO:
         [Job 1] Cached (workflow_qsm.sub-basel-3depi-P001.ses-1.run-1.func_read-json).
220727-12:21:24,517 nipype.workflow INFO:
         [Job 2] Cached (workflow_qsm.sub-basel-3depi-P001.ses-1.run-1.python_threshold-masking).
220727-12:21:24,619 nipype.workflow INFO:
         [Job 5] Cached (workflow_qsm.sub-goldseed-phantom.ses-1.run-1.python_threshold-masking).
220727-12:21:26,417 nipype.workflow INFO:
         [MultiProc] Running 0 tasks, and 48 jobs ready. Free memory (GB): 22.10/22.10, Free processors: 4/4.
220727-12:21:26,470 nipype.workflow INFO:
         [Job 6] Cached (workflow_qsm.sub-monique-3depi-3dgre-tests.ses-1.run-10.nibabel_scale-phase).
220727-12:21:26,488 nipype.workflow INFO:
         [Job 7] Cached (workflow_qsm.sub-monique-3depi-3dgre-tests.ses-1.run-10.func_read-json).
220727-12:21:26,504 nipype.workflow INFO:
         [Job 8] Cached (workflow_qsm.sub-monique-3depi-3dgre-tests.ses-1.run-10.python_threshold-masking).
220727-12:21:26,575 nipype.workflow INFO:
         [Job 11] Cached (workflow_qsm.sub-prostate-z0755228.ses-20211108.run-1.python_threshold-masking).
220727-12:21:28,419 nipype.workflow INFO:
         [MultiProc] Running 0 tasks, and 49 jobs ready. Free memory (GB): 22.10/22.10, Free processors: 4/4.
220727-12:21:28,497 nipype.workflow INFO:
         [Job 14] Cached (workflow_qsm.sub-qsmchallenge2019-sim1.ses-1.run-1.python_threshold-masking).
220727-12:21:28,543 nipype.workflow INFO:
         [Job 17] Cached (workflow_qsm.sub-sahmri-3dgre-001.ses-1.run-1.python_threshold-masking).
220727-12:21:28,568 nipype.workflow INFO:
         [Job 18] Cached (workflow_qsm.sub-basel-3depi-P001.ses-1.run-1.func_repeat-mask).
220727-12:21:28,607 nipype.workflow INFO:
         [Job 20] Cached (workflow_qsm.sub-monique-3depi-3dgre-tests.ses-1.run-10.func_repeat-mask).
220727-12:21:30,421 nipype.workflow INFO:
         [MultiProc] Running 0 tasks, and 57 jobs ready. Free memory (GB): 22.10/22.10, Free processors: 4/4.
220727-12:21:30,573 nipype.workflow INFO:
         [Job 24] Cached (workflow_qsm.sub-basel-3depi-P001.ses-1.run-1.tgv-qsm_filled).
220727-12:21:30,632 nipype.workflow INFO:
         [Job 25] Cached (workflow_qsm.sub-basel-3depi-P001.ses-1.run-1.tgv-qsm_intermediate).
220727-12:21:30,710 nipype.workflow INFO:
         [Job 28] Cached (workflow_qsm.sub-monique-3depi-3dgre-tests.ses-1.run-10.tgv-qsm_filled).
220727-12:21:30,778 nipype.workflow INFO:
         [Job 29] Cached (workflow_qsm.sub-monique-3depi-3dgre-tests.ses-1.run-10.tgv-qsm_intermediate).
220727-12:21:32,423 nipype.workflow INFO:
         [MultiProc] Running 0 tasks, and 66 jobs ready. Free memory (GB): 22.10/22.10, Free processors: 4/4.
220727-12:21:32,485 nipype.workflow INFO:
         [Node] Setting-up "workflow_qsm.sub-basel-3depi-P001.ses-1.run-1.nibabel_qsm-filled-average" in "/neurodesktop-storage/data/battery_twopass_magnitude-based-hole-1/workflow_qsm/sub-basel-3depi-P001/ses-1/run-1/nibabel_qsm-filled-average".
220727-12:21:32,501 nipype.workflow INFO:
         [Node] Setting-up "workflow_qsm.sub-basel-3depi-P001.ses-1.run-1.nibabel_qsm-average" in "/neurodesktop-storage/data/battery_twopass_magnitude-based-hole-1/workflow_qsm/sub-basel-3depi-P001/ses-1/run-1/nibabel_qsm-average".
220727-12:21:32,511 nipype.workflow ERROR:
         Node nibabel_twopass failed to run on host a24eeb46bb08.
220727-12:21:32,512 nipype.workflow ERROR:
         Saving crash info to /neurodesktop-storage/qsmxt/crash-20220727-122132-root-nibabel_twopass-c31aa3aa-5405-41e5-b032-5880bb429984.pklz
Traceback (most recent call last):
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/plugins/multiproc.py", line 292, in _send_procs_to_workers
    num_subnodes = self.procs[jobid].num_subnodes()
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1309, in num_subnodes
    self._get_inputs()
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1323, in _get_inputs
    super(MapNode, self)._get_inputs()
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 609, in _get_inputs
    self.set_input(key, deepcopy(output_value))
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1158, in set_input
    self._set_mapnode_input(parameter, deepcopy(val))
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/nodes.py", line 1165, in _set_mapnode_input
    setattr(self._inputs, name, newvalue)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 426, in validate
    value = super(MultiObject, self).validate(objekt, name, newvalue)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/traits/trait_types.py", line 2515, in validate
    return TraitListObject(self, object, name, value)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/traits/trait_list_object.py", line 585, in __init__
    notifiers=[self.notifier],
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/traits/trait_list_object.py", line 213, in __init__
    super().__init__(self.item_validator(item) for item in iterable)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/traits/trait_list_object.py", line 213, in <genexpr>
    super().__init__(self.item_validator(item) for item in iterable)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/traits/trait_list_object.py", line 865, in _item_validator
    return trait_validator(object, self.name, value)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/traits/base_trait_handler.py", line 75, in error
    object, name, self.full_info(object, name, value), value
traits.trait_errors.TraitError: Each element of the 'in_file2' trait of a DynamicTraitedSpec instance must be a pathlike object or string representing an existing file, but a value of '/neurodesktop-storage/data/battery_twopass_magnitude-based-hole-1/workflow_qsm/sub-basel-3depi-P001/ses-1/run-1/nibabel_scale-phase/mapflow/_nibabel_scale-phase0/sub-basel-3depi-P001_ses-1_run-1_part-phase_T2starw_scaled_qsm-filled_000.nii' <class 'str'> was specified.

Error setting node input:
Node: nibabel_twopass
input: in_file2
results_file: /neurodesktop-storage/data/battery_twopass_magnitude-based-hole-1/workflow_qsm/sub-basel-3depi-P001/ses-1/run-1/tgv-qsm_filled/result_tgv-qsm_filled.pklz
value: ['/neurodesktop-storage/data/battery_twopass_magnitude-based-hole-1/workflow_qsm/sub-basel-3depi-P001/ses-1/run-1/nibabel_scale-phase/mapflow/_nibabel_scale-phase0/sub-basel-3depi-P001_ses-1_run-1_part-phase_T2starw_scaled_qsm-filled_000.nii']
```

**Comment by korbinian90** [comment]
I just pulled the new container (nice! only 8.7GB instead of 24GB) and updated to the newest commit from today.

Master version [3313733](https://github.com/QSMxT/QSMxT/commit/3313733cacd6dc64eff2f2bd95288a24cb500abf)

```
(base) root@1e3f852a3ea0:/neurodesktop-storage/qsmxt# python3 ./run_2_qsm.py ../data/bids ../data/test
INFO: Running QSMxT v1.1.12-1-g331373 (commit date: Thu Jul 28 05:17:03 2022 +000)
INFO: Command: ./run_2_qsm.py ../data/bids ../data/test
INFO: Running with 4 procesors.
Traceback (most recent call last):
  File "./run_2_qsm.py", line 643, in <module>
    wf = init_workflow()
  File "./run_2_qsm.py", line 38, in init_workflow
    wf = Workflow("workflow_qsm", base_dir=args.work_dir)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 57, in __init__
    import networkx as nx
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/networkx/__init__.py", line 81, in <module>
    from networkx import algorithms
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/networkx/algorithms/__init__.py", line 81, in <module>
    from networkx.algorithms import tree
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/networkx/algorithms/tree/__init__.py", line 1, in <module>
    from .branchings import *
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/networkx/algorithms/tree/branchings.py", line 30, in <module>
    from dataclasses import dataclass, field
ModuleNotFoundError: No module named 'dataclasses'
```

I tried to install dataclasses,

```
(base) root@1e3f852a3ea0:/neurodesktop-storage/qsmxt# pip install dataclasses
Collecting dataclasses
  Downloading dataclasses-0.8-py3-none-any.whl (19 kB)
Installing collected packages: dataclasses
Successfully installed dataclasses-0.8
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```
But more errors followed:
```
(base) root@1e3f852a3ea0:/neurodesktop-storage/qsmxt# python3 ./run_2_qsm.py ../data/bids ../data/test
INFO: Running QSMxT v1.1.12-1-g331373 (commit date: Thu Jul 28 05:17:03 2022 +000)
INFO: Command: ./run_2_qsm.py ../data/bids ../data/test
INFO: Running with 4 procesors.
WARNING: Skipping run sub-170705-134431-std-1312211075243167001/ses-1/run-1 - an unequal number of JSON and phase files are present.
220728-13:33:29,695 nipype.utils WARNING:
         A newer version (1.8.3) of nipy/nipype is available. You are using 1.6.0
220728-13:33:29,909 nipype.workflow INFO:
         Workflow workflow_qsm settings: ['check', 'execution', 'logging', 'monitoring']
220728-13:33:29,967 nipype.workflow INFO:
         Running in parallel.
Traceback (most recent call last):
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 423, in _generate_dependency_list
    graph, nodelist=self.procs, format="lil"
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/networkx/convert_matrix.py", line 1020, in to_scipy_sparse_matrix
    G, nodelist=nodelist, dtype=dtype, weight=weight, format=format
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/networkx/convert_matrix.py", line 907, in to_scipy_sparse_array
    A = sp.sparse.coo_array((data, (row, col)), shape=(nlen, nlen), dtype=dtype)
AttributeError: module 'scipy.sparse' has no attribute 'coo_array'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./run_2_qsm.py", line 696, in <module>
    'n_procs': args.n_procs
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/engine/workflows.py", line 632, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 121, in run
    self._generate_dependency_list(graph)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/nipype/pipeline/plugins/base.py", line 426, in _generate_dependency_list
    self.depidx = nx.to_scipy_sparse_matrix(graph, nodelist=self.procs)
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/networkx/convert_matrix.py", line 1020, in to_scipy_sparse_matrix
    G, nodelist=nodelist, dtype=dtype, weight=weight, format=format
  File "/opt/miniconda-4.7.12.1/lib/python3.6/site-packages/networkx/convert_matrix.py", line 907, in to_scipy_sparse_array
    A = sp.sparse.coo_array((data, (row, col)), shape=(nlen, nlen), dtype=dtype)
AttributeError: module 'scipy.sparse' has no attribute 'coo_array'
```
I tried a `conda update scipy`, but that is fruitlessly running since an hour, trying to solve the environment. Probably you have a better solution ;)

**Comment by astewartau** [comment]
Thanks for these reports! The dataclasses problem is related to the networkx package, as nipype requires a particular version. This has now been fixed in the build recipe and the workflow tests now pass. :)
