### ISSUE TITLE
freesurfer crash in pbs

### ISSUE THREAD

**Issue by astewartau** [QSMxT/QSMxT#8]
```
~/imaging_pipelines: nipypecli crash crash*recon_all*


File: /gpfs1/homes/uqaste15/imaging_pipelines/crash-20210111-125438-uqaste15-recon_all.a0-af37f00f-a972-4a82-83ef-8dc617681b21.pklz
Node: segmentation.recon_all
Working directory: /gpfs1/scratch/30days/uqaste15/work/sahmri_segmentation_test/segmentation/_subject_id_sub-0001/recon_all


Node inputs:

FLAIR_file = <undefined>
T1_files = [['/gpfs1/homes/uqaste15/imaging_pipelines/bids/sahmri/sub-0001/anat/sub-0001_acq-t1_run-1_magnitude.nii.gz']]
T2_file = <undefined>
args = <undefined>
big_ventricles = <undefined>
brainstem = <undefined>
directive = all
environ = {}
expert = <undefined>
flags = <undefined>
hemi = <undefined>
hippocampal_subfields_T1 = <undefined>
hippocampal_subfields_T2 = <undefined>
hires = <undefined>
mprage = <undefined>
mri_aparc2aseg = <undefined>
mri_ca_label = <undefined>
mri_ca_normalize = <undefined>
mri_ca_register = <undefined>
mri_edit_wm_with_aseg = <undefined>
mri_em_register = <undefined>
mri_fill = <undefined>
mri_mask = <undefined>
mri_normalize = <undefined>
mri_pretess = <undefined>
mri_remove_neck = <undefined>
mri_segment = <undefined>
mri_segstats = <undefined>
mri_tessellate = <undefined>
mri_watershed = <undefined>
mris_anatomical_stats = <undefined>
mris_ca_label = <undefined>
mris_fix_topology = <undefined>
mris_inflate = <undefined>
mris_make_surfaces = <undefined>
mris_register = <undefined>
mris_smooth = <undefined>
mris_sphere = <undefined>
mris_surf2vol = <undefined>
mrisp_paint = <undefined>
openmp = 16
parallel = True
subject_id = ['sub-0001']
subjects_dir = <undefined>
talairach = <undefined>
use_FLAIR = <undefined>
use_T2 = <undefined>
xopts = <undefined>



Traceback: 
Traceback (most recent call last):
  File "/gpfs1/homes/uqaste15/imaging_pipelines/work/sahmri_segmentation_test/segmentation/batch/pyscript_20210111_125302_segmentation_recon_all.a0.py", line 38, in <module>
    result = info['node'].run(updatehash=info['updatehash'])
  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1386, in _run_interface
    self.config["execution"]["stop_on_first_crash"]
  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 1295, in _collate_results
    "Subnodes of node: %s failed:\n%s" % (self.name, "\n".join(msg))
Exception: Subnodes of node: recon_all failed:
Subnode 0 failed
Error: Traceback (most recent call last):

  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/pipeline/engine/utils.py", line 94, in nodelist_runner
    result = node.run(updatehash=updatehash)

  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)

  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)

  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)

  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 397, in run
    runtime = self._run_interface(runtime)

  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 792, in _run_interface
    self.raise_exception(runtime)

  File "/home/uqaste15/miniconda3/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 723, in raise_exception
    ).format(**runtime.dictcopy())

RuntimeError: Command:
recon-all -all -i /gpfs1/homes/uqaste15/imaging_pipelines/bids/sahmri/sub-0001/anat/sub-0001_acq-t1_run-1_magnitude.nii.gz -openmp 16 -parallel -subjid sub-0001 -sd /gpfs1/scratch/30days/uqaste15/work/sahmri_segmentation_test/segmentation/_subject_id_sub-0001/recon_all/mapflow/_recon_all0
Standard output:
ERROR: must specify a subject id
Standard error:
mktemp: failed to create file via template ‘/state/partition1/pbs/tmpdir/pbs.520113.awonmgr2/tmp.XXXXXXXXXX’: No such file or directory
mktemp: failed to create file via template ‘/state/partition1/pbs/tmpdir/pbs.520113.awonmgr2/tmp.XXXXXXXXXX’: No such file or directory
Traceback (most recent call last):
  File "/opt/freesurfer-7.1.0/python/scripts/rca-config2csh", line 20, in <module>
    configfile = sys.argv[1]
IndexError: list index out of range
Return code: 1

```

**Comment by stebo85** [comment]
is this problem solved after adding /state to the singularity bindpath :?

**Comment by astewartau** [comment]
Yes, that was it. Closing this.
