### ISSUE TITLE
Error accessing arg["mag"] when not supplied in romeo_voxelquaility.jl

### ISSUE THREAD

**Issue by pfuchs** [QSMxT/QSMxT#98]
I'm running into the following error using romeo_voxelquality.jl. As can be seen from the below command no "--mag" is supplied in the call, but the script still (erroneously) tries to access a mag_files path variable. I'm not exactly sure on why "if !isnothing(args["mag"])" fails, perhaps someone can look into the default behaviour upon supplying no magnitude image to this.

```code
/neurodesktop-storage# /opt/QSMxT/scripts/romeo_voxelquality.jl --TEs '[0.02501 0.04044 0.05587]' --phase /neurodesktop-storage/02_qsm_output/workflow_qsm/sub-221207100856STD131221107524367073/ses-1/run-03/nibabel_as-canonical/mapflow/_nibabel_as-canonical1/sub-221207100856STD131221107524367073_ses-1_run-03_echo-02_part-phase_MEGRE_scaled_canonical.nii --output sub-221207100856STD131221107524367073_ses-1_run-03_echo-02_part-phase_MEGRE_scaled_canonical_romeo_voxelquality.nii --type grad+second
ERROR: LoadError: BoundsError: attempt to access 0-element Vector{Any} at index [1]
Stacktrace:
 [1] getindex(A::Vector{Any}, i1::Int64)
   @ Base ./array.jl:801
 [2] top-level scope
   @ /opt/QSMxT/scripts/romeo_voxelquality.jl:77
in expression starting at /opt/QSMxT/scripts/romeo_voxelquality.jl:44
```

**Comment by astewartau** [comment]
Hi @pfuchs, thanks for raising this! 

I've implemented a fix in v3.0.1, which should be available on CVMFS and DockerHub shortly. 

So that I can test this properly in future, can you please let me know what settings you used? It would be enough to paste the contents of `command.txt` from your QSM output directory. Secondly, do you actually have any magnitude files in your BIDS directory? Magnitude files should not be required, but knowing this will help me write an automated test.

**Comment by pfuchs** [comment]
Hi Ashley,

The command being run is

```code
run_2_qsm.py /neurodesktop-storage/01_bids /neurodesktop-storage/02_qsm_output --premade 'bet' --two_pass off --auto_yes
```

And the issue outlined above is fixed in 3.0.1, however I'm running into the following now:

```code
Cmdline:
	/opt/QSMxT/scripts/romeo_unwrapping.jl -B --no-rescale --phase-offset-correction --phase /neurodesktop-storage/02_qsm_output/workflow_qsm/sub-230222111634STD131221107524367073/ses-1/run-09/mrt_romeo_combine/multi-echo-phase.nii -t '[22.8 62.61 102.42 142.23]'
Stdout:

Stderr:
	┌ Warning: robustmask was chosen but no magnitude is available. No mask is used!
	└ @ RomeoApp /opt/julia_depot/packages/RomeoApp/4dkTb/src/caller.jl:63
	ERROR: LoadError: Number of chosen echoes is 7 (7 in .nii data), but 4 TEs were specified!
	Stacktrace:
	 [1] error(s::String)
	   @ Base ./error.jl:33
	 [2] load_data_and_resolve_args!(settings::Dict{String, Any})
	   @ RomeoApp /opt/julia_depot/packages/RomeoApp/4dkTb/src/caller.jl:112
	 [3] unwrapping_main(args::Vector{String}; version::String)
	   @ RomeoApp /opt/julia_depot/packages/RomeoApp/4dkTb/src/caller.jl:3
	 [4] unwrapping_main(args::Vector{String})
	   @ RomeoApp /opt/julia_depot/packages/RomeoApp/4dkTb/src/caller.jl:2
	 [5] top-level scope
	   @ /opt/QSMxT/scripts/romeo_unwrapping.jl:3
	in expression starting at /opt/QSMxT/scripts/romeo_unwrapping.jl:3
Traceback:
	Traceback (most recent call last):
	  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 400, in run
	    outputs = self.aggregate_outputs(runtime)
	  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 429, in aggregate_outputs
	    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
	  File "/opt/QSMxT/interfaces/nipype_interface_romeo.py", line 69, in _list_outputs
	    os.rename(os.path.join(os.getcwd(), "B0.nii"), frequency_path)
	FileNotFoundError: [Errno 2] No such file or directory: '/neurodesktop-storage/02_qsm_output/workflow_qsm/sub-230222111634STD131221107524367073/ses-1/run-09/mrt_romeo_combine/B0.nii' -> '/neurodesktop-storage/02_qsm_output/workflow_qsm/sub-230222111634STD131221107524367073/ses-1/run-09/mrt_romeo_combine/sub-230222111634STD131221107524367073_ses-1_run-09_echo-01_part-phase_MEGRE_scaled_canonical_romeo-b0map.nii'



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/QSMxT/run_2_qsm.py", line 1491, in <module>
    wf.run(
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 224, in run
    raise error from cause
RuntimeError: 10 raised. Re-raising first.
```

Magnitudes are present in the BIDS directory. The problem seems to stem from this sequence as it acquired 7 volumes (of each 4 echoes), which seem to be stacked by dcm2niix into 4 separate (for the echoes) nifti files of dimensions Nx x Ny x Nz x Nvol. And ROMEO takes the 4th dimension to be the number of echoes, when in this case the QSM should be computed for each volume separately, or at least that would be my expected behaviour.

**Comment by astewartau** [comment]
Sorry for the delay in getting back to you on this. 

For now, you should be able to get around this using `--combine_phase off` to disable phase combination and process each echo separately. Do I understand correctly that there are multiple volumes for each echo? Do you know what each volume represents and if there is information about this in the DICOM or NIfTI headers? This might help me determine how to automatically process these correctly for combining the echoes or otherwise.

**Comment by pfuchs** [comment]
Hi Ashley, 

No worries, not in a rush to get this working, just trying to help out by testing the toolbox ;-). So this dataset is essentially 7 volumes of 4 echos each, acquired sequentially. It therefore does not make sense to look at it as 7 copies of echo 1, then 7 copies of echo 2 , etc. but rather volume 1 echoes 1...4, volume 2 echoes 1...4. I'm not exactly sure why dcm2niix matches them per echo time (although that is the only way to preserve this information int he nifti header). usually we run dcm2niix with the "-m" option to just merge the entire thing into a Nx x Ny x Nz x (Ne*Na) where the echoes are stacked in the way I described, i.e.[ v1:e1,v1:e2,v1:e3,v1:e4,v2:e1,v2:e2,v2:e3,v2:e4...].

I'll run it with --combine_phase off to check if that is the only issue, but it would be great to be able to combine echoes on a per-volume basis and compute qsms per volume. Maybe there is a better way to do this, by separating them out into "runs" in the BIDS format, which would fix the downstream problems automatically I wager.

**Comment by pfuchs** [comment]
Re-running it with --combine_phase off still yields a Romeo error

```
Cmdline:
	/opt/QSMxT/scripts/romeo_unwrapping.jl -B --no-rescale --phase-offset-correction --phase /neurodesktop-storage/02_qsm_output/workflow_qsm/sub-230222111634STD131221107524367073/ses-1/run-02/qsm-intermediate_workflow/mrt_romeo/multi-echo-phase.nii -t '[15.2 36.45 57.7 78.95]'
Stdout:

Stderr:
	┌ Warning: robustmask was chosen but no magnitude is available. No mask is used!
	└ @ RomeoApp /opt/julia_depot/packages/RomeoApp/4dkTb/src/caller.jl:63
	ERROR: LoadError: Number of chosen echoes is 15 (15 in .nii data), but 4 TEs were specified!
	Stacktrace:
	 [1] error(s::String)
	   @ Base ./error.jl:33
	 [2] load_data_and_resolve_args!(settings::Dict{String, Any})
	   @ RomeoApp /opt/julia_depot/packages/RomeoApp/4dkTb/src/caller.jl:112
	 [3] unwrapping_main(args::Vector{String}; version::String)
	   @ RomeoApp /opt/julia_depot/packages/RomeoApp/4dkTb/src/caller.jl:3
	 [4] unwrapping_main(args::Vector{String})
	   @ RomeoApp /opt/julia_depot/packages/RomeoApp/4dkTb/src/caller.jl:2
	 [5] top-level scope
	   @ /opt/QSMxT/scripts/romeo_unwrapping.jl:3
	in expression starting at /opt/QSMxT/scripts/romeo_unwrapping.jl:3
Traceback:
	Traceback (most recent call last):
	  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 400, in run
	    outputs = self.aggregate_outputs(runtime)
	  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 429, in aggregate_outputs
	    predicted_outputs = self._list_outputs()  # Predictions from _list_outputs
	  File "/opt/QSMxT/interfaces/nipype_interface_romeo.py", line 69, in _list_outputs
	    os.rename(os.path.join(os.getcwd(), "B0.nii"), frequency_path)
	FileNotFoundError: [Errno 2] No such file or directory: '/neurodesktop-storage/02_qsm_output/workflow_qsm/sub-230222111634STD131221107524367073/ses-1/run-02/qsm-intermediate_workflow/mrt_romeo/B0.nii' -> '/neurodesktop-storage/02_qsm_output/workflow_qsm/sub-230222111634STD131221107524367073/ses-1/run-02/qsm-intermediate_workflow/mrt_romeo/sub-230222111634STD131221107524367073_ses-1_run-02_echo-01_part-phase_MEGRE_scaled_canonical_romeo-b0map.nii'



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/QSMxT/run_2_qsm.py", line 1491, in <module>
    wf.run(
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/opt/miniconda-4.7.12.1/lib/python3.8/site-packages/nipype/pipeline/plugins/base.py", line 224, in run
    raise error from cause
RuntimeError: 20 raised. Re-raising first.
```

so somehow even with --combine_phase off there is part of the pipeline using an echo-combination (for robust masking it seems).

**Comment by astewartau** [comment]
Hi @pfuchs - thanks again for raising this. This is definitely happening because the conversion to BIDS has left some of the images as 4D volume series rather than BIDS-compliant 3D volumes. I have some time to look at this more closely. Can you share an example dataset so I can understand better how the data structure is represented through the DICOMs? It may be a bug in how dcm2niix is converting them. What type of scanner was used?

**Comment by pfuchs** [comment]
Sorry for only getting back to you now, a Siemens scanner was used. The data is formatted identical to how the [Open Multi-Echo Datasets](https://me-ica.github.io/multi-echo-data-analysis/content/Multi_Echo_Datasets.html), or more specifically [Multi-Echo Cambridge dataset](https://openneuro.org/datasets/ds000258/versions/1.0.1) are structured (except that they also contain the phase information, and are of less volumes than the fmri acquisitions as it only concerns averaging of 5-10 volumes at most in our case.

I'll see if I can share some DICOMS with you as well but will have to get approval for that from our clinical partners. Hope the above datasets give you an idea of the structure of the nifti/bids layout after conversion.

**Comment by astewartau** [comment]
Closing this long-standing issue — it relates to the v3-era handling of 4D multi-echo volume series, and DICOM/BIDS conversion and phase handling have changed substantially since (most recently in the v9 rewrite). If you still hit this on a current release, please open a fresh issue with an example and we'll take a look. Thanks again for helping test, @pfuchs!
